# Generated by Django 3.2 on 2023-07-12 13:58

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(choices=[('Legal', 'Legal'), ('Risk Audit Compliance', 'RAC'), ('Human Recourse', 'HR'), ('Marketing', 'Marketing'), ('Technology', 'Tech'), ('Finance', 'Finance'), ('Customer Experience', 'Customer Experience'), ('Financial', 'Financial'), ('Business Development', 'Business Development'), ('commercial', 'commercial'), ('security', 'security'), ('HSE', 'HSE'), ('Customer Service', 'CS'), ('Operation', 'Operation'), ('Product', 'Product'), ('Logistic, Express', 'Logistic, Express')], max_length=256),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[users.models.validate_email], verbose_name='email address'),
        ),
    ]
