# Generated by Django 3.2 on 2022-09-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rand_text',
            field=models.CharField(default='fff', max_length=32),
        ),
    ]
