# Generated by Django 3.2 on 2023-07-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230712_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='department',
            field=models.CharField(choices=[('Legal', 'Legal'), ('Risk Audit Compliance', 'RAC'), ('Human Recourse', 'HR'), ('Marketing', 'Marketing'), ('Technology', 'Tech'), ('Finance', 'Finance'), ('Customer Experience', 'Customer Experience'), ('Financial', 'Financial'), ('Business Development', 'Business Development'), ('commercial', 'commercial'), ('security', 'security'), ('HSE', 'HSE'), ('Customer Service', 'CS'), ('Operation', 'Operation'), ('Product', 'Product'), ('Logistic, Express', 'Logistic, Express'), ('Manager', 'Manager')], max_length=256),
        ),
    ]
