# Generated by Django 3.2.6 on 2022-08-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('Legal', 'Legal'), ('RAC', 'Risk Audit Compliance'), ('HR', 'Human Recourse'), ('Marketing', 'Marketing'), ('Tech', 'Technology'), ('Finance', 'Finance'), ('User Experience', 'User Experience'), ('Financial', 'Financial'), ('Business Development', 'Business Development'), ('Operation', 'Operation')], max_length=256, null=True),
        ),
    ]
