# Generated by Django 3.2 on 2022-09-19 07:32

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(max_length=11, null=True, unique=True, validators=[users.models.validate_phone_number]),
        ),
    ]
