# Generated by Django 3.2 on 2022-09-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='member_profile_images/'),
        ),
    ]
