# Generated by Django 3.2 on 2022-09-19 10:52

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_member_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_image',
            field=models.ImageField(default=users.models.get_default_profile_image, upload_to='member_profile_images/'),
        ),
    ]
