# Generated by Django 3.2 on 2022-09-07 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=256)),
                ('flowchart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flowchart.flowchart')),
            ],
        ),
    ]
