# Generated by Django 3.2 on 2022-08-30 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0002_auto_20220830_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowchart',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='incident_number',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
