# Generated by Django 3.2 on 2022-08-30 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0003_auto_20220830_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowchart',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loc', to='flowchart.location'),
        ),
    ]
