# Generated by Django 3.2 on 2022-09-07 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0003_alter_incident_flowchart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='flowchart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inc', to='flowchart.flowchart'),
        ),
    ]
