# Generated by Django 3.2 on 2022-09-07 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0004_alter_incident_flowchart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Incident',
        ),
    ]
