# Generated by Django 3.2 on 2022-08-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0004_alter_flowchart_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowchart',
            name='status',
            field=models.CharField(choices=[('CL', 'Closed'), ('IN', 'In Progress')], default='CL', max_length=2),
        ),
    ]
