# Generated by Django 3.2 on 2022-09-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0005_delete_incident'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowchart',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
