# Generated by Django 3.2 on 2022-08-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0005_flowchart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flowchart',
            name='status',
        ),
        migrations.AddField(
            model_name='flowchart',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
