MATTERMOST_ACCOUNTS_PEOPLE_PROTEST = []
MATTERMOST_ACCOUNTS_STAFF_STRIKE = []
MATTERMOST_ACCOUNTS_SELLER_STRIKE = []
MATTERMOST_ACCOUNTS_DRIVER_STRIKE = []
MATTERMOST_ACCOUNTS_MEDIA_CRISIS = []
MATTERMOST_ACCOUNTS_EARTH_QUAKE = []
MATTERMOST_ACCOUNTS_FIRE = []
MATTERMOST_ACCOUNTS_DATA_LEAKAGE = []

MATTERMOST_GROUP_NAME_PEOPLE_PROTEST = ''
MATTERMOST_GROUP_NAME_STAFF_STRIKE = ''
MATTERMOST_GROUP_NAME_SELLER_STRIKE = ''
MATTERMOST_GROUP_NAME_DRIVER_STRIKE = ''
MATTERMOST_GROUP_NAME_MEDIA_CRISIS = ''
MATTERMOST_GROUP_NAME_EARTH_QUAKE = ''
MATTERMOST_GROUP_NAME_FIRE = ''
MATTERMOST_GROUP_NAME_DATA_LEAKAGE = ''

MATTERMOST_GROUP_NAME_TEST = 'bcm12'
MATTERMOST_TEAM_NAME_TEST = 'rac'
MATTERMOST_ACCOUNTS_TEST = ['omid.asadi', 'amirreza.ghafari', 'h.pourhaji']

CALLER_SERVER_ADDRESS = ''
