# Generated by Django 3.2 on 2022-08-15 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(max_length=256)),
                ('figure', models.CharField(blank=True, choices=[('Procedure', 'Procedure'), ('Cylinder1', 'Cylinder1'), ('Terminator', 'Terminator'), ('CreateRequest', 'CreateRequest'), ('Document', 'Document'), ('Diamond', 'Diamond')], default=None, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(choices=[('pink', 'pink'), ('green', 'green'), ('black', 'black'), ('blue', 'blue'), ('red', 'red')], default='black', max_length=256)),
                ('thickness', models.IntegerField(blank=True, default=4, null=True)),
                ('fill', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('loc_height', models.IntegerField(blank=True, null=True)),
                ('loc_length', models.IntegerField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_conditional', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BlockGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Flowchart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalTransition',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('updated_date', models.DateTimeField(blank=True, editable=False)),
                ('color', models.CharField(choices=[('pink', 'pink'), ('green', 'green'), ('black', 'black'), ('blue', 'blue'), ('red', 'red')], default='black', max_length=256)),
                ('is_active', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('end_block', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='diagram.block')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('start_block', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='diagram.block')),
            ],
            options={
                'verbose_name': 'historical transition',
                'verbose_name_plural': 'historical transitions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalBlock',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('updated_date', models.DateTimeField(blank=True, editable=False)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('label', models.CharField(max_length=256)),
                ('figure', models.CharField(blank=True, choices=[('Procedure', 'Procedure'), ('Cylinder1', 'Cylinder1'), ('Terminator', 'Terminator'), ('CreateRequest', 'CreateRequest'), ('Document', 'Document'), ('Diamond', 'Diamond')], default=None, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(choices=[('pink', 'pink'), ('green', 'green'), ('black', 'black'), ('blue', 'blue'), ('red', 'red')], default='black', max_length=256)),
                ('thickness', models.IntegerField(blank=True, default=4, null=True)),
                ('fill', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('loc_height', models.IntegerField(blank=True, null=True)),
                ('loc_length', models.IntegerField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_conditional', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('flowchart', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='diagram.flowchart')),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='diagram.blockgroup')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical block',
                'verbose_name_plural': 'historical blocks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='block',
            name='flowchart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowchart', to='diagram.flowchart'),
        ),
        migrations.AddField(
            model_name='block',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagram.blockgroup'),
        ),
        migrations.AddField(
            model_name='block',
            name='user_groups',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Group'),
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(choices=[('pink', 'pink'), ('green', 'green'), ('black', 'black'), ('blue', 'blue'), ('red', 'red')], default='black', max_length=256)),
                ('is_active', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('end_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_block', to='diagram.block')),
                ('start_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_block', to='diagram.block')),
            ],
            options={
                'unique_together': {('start_block', 'end_block')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='block',
            unique_together={('flowchart', 'label')},
        ),
    ]
