# Generated by Django 3.2 on 2023-07-05 18:58

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(max_length=256)),
                ('figure', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('color', models.CharField(default='black', max_length=256)),
                ('loc_height', models.IntegerField(blank=True, null=True)),
                ('loc_length', models.IntegerField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_pre_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_conditional', models.BooleanField(default=False)),
                ('rand_text', models.CharField(default=None, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=256, null=True)),
                ('text', models.TextField()),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalBlock',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('updated_date', models.DateTimeField(blank=True, editable=False)),
                ('created_date', models.DateTimeField(blank=True, editable=False)),
                ('label', models.CharField(max_length=256)),
                ('figure', models.CharField(blank=True, default=None, max_length=256, null=True)),
                ('color', models.CharField(default='black', max_length=256)),
                ('loc_height', models.IntegerField(blank=True, null=True)),
                ('loc_length', models.IntegerField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_pre_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_conditional', models.BooleanField(default=False)),
                ('rand_text', models.CharField(default=None, max_length=16, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical block',
                'verbose_name_plural': 'historical blocks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalComment',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=256, null=True)),
                ('text', models.TextField()),
                ('updated_date', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical comment',
                'verbose_name_plural': 'historical comments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(default='black', max_length=256)),
                ('is_active', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('end_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_transition', to='diagram.block')),
                ('start_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='out_transition', to='diagram.block')),
            ],
        ),
    ]
