# Generated by Django 4.1 on 2022-08-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='figure',
            field=models.CharField(choices=[('Procedure', 'Procedure'), ('Cylinder1', 'Cylinder1'), ('Terminator', 'Terminator'), ('CreateRequest', 'CreateRequest'), ('Document', 'Document')], max_length=256, null=True),
        ),
    ]
