# Generated by Django 3.2 on 2022-09-05 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='rand_text',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='historicalblock',
            name='rand_text',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
