# Generated by Django 3.2 on 2022-08-16 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0001_initial'),
        ('diagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='flowchart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowchart', to='flowchart.flowchart'),
        ),
        migrations.AlterField(
            model_name='historicalblock',
            name='flowchart',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flowchart.flowchart'),
        ),
        migrations.DeleteModel(
            name='Flowchart',
        ),
    ]
