# Generated by Django 3.2 on 2022-08-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalblock',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
