# Generated by Django 3.2 on 2022-09-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0002_auto_20220905_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='rand_text',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='historicalblock',
            name='rand_text',
            field=models.CharField(default=None, max_length=16, null=True),
        ),
    ]
