# Generated by Django 3.2 on 2022-08-16 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0001_initial'),
        ('diagram', '0002_auto_20220816_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransition',
            name='flowchart',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flowchart.flowchart'),
        ),
        migrations.AddField(
            model_name='transition',
            name='flowchart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transition_flowchart', to='flowchart.flowchart'),
        ),
    ]
