# Generated by Django 4.1 on 2022-08-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0003_alter_block_figure'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='block',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='block',
            name='color',
            field=models.CharField(choices=[('pink', 'pink'), ('green', 'green')], default='green', max_length=256),
        ),
    ]
