# Generated by Django 3.2 on 2022-09-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0003_auto_20220905_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='label',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='label',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
