# Generated by Django 3.2 on 2022-08-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0003_auto_20220813_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='color',
            field=models.CharField(choices=[('pink', 'pink'), ('green', 'green'), ('black', 'black'), ('blue', 'blue'), ('red', 'red')], default='black', max_length=256),
        ),
        migrations.AlterField(
            model_name='historicalblock',
            name='color',
            field=models.CharField(choices=[('pink', 'pink'), ('green', 'green'), ('black', 'black'), ('blue', 'blue'), ('red', 'red')], default='black', max_length=256),
        ),
        migrations.AlterField(
            model_name='historicaltransition',
            name='color',
            field=models.CharField(choices=[('pink', 'pink'), ('green', 'green'), ('black', 'black'), ('blue', 'blue'), ('red', 'red')], default='black', max_length=256),
        ),
        migrations.AlterField(
            model_name='transition',
            name='color',
            field=models.CharField(choices=[('pink', 'pink'), ('green', 'green'), ('black', 'black'), ('blue', 'blue'), ('red', 'red')], default='black', max_length=256),
        ),
    ]
