# Generated by Django 3.2 on 2022-08-16 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0001_initial'),
        ('diagram', '0003_auto_20220816_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transition',
            name='flowchart',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transition_flowchart', to='flowchart.flowchart'),
            preserve_default=False,
        ),
    ]
