# Generated by Django 4.1 on 2022-08-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0004_block_active_block_approved_alter_block_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transition',
            name='done',
        ),
        migrations.AlterField(
            model_name='block',
            name='color',
            field=models.CharField(choices=[('pink', 'pink'), ('green', 'green')], default='red', max_length=256),
        ),
    ]
