# Generated by Django 3.2 on 2022-08-17 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowchart', '0001_initial'),
        ('diagram', '0004_alter_transition_flowchart'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transition',
            unique_together={('start_block', 'end_block', 'flowchart')},
        ),
    ]
