# Generated by Django 3.2 on 2022-09-07 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0004_auto_20220907_0823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='fill',
        ),
        migrations.RemoveField(
            model_name='block',
            name='thickness',
        ),
        migrations.RemoveField(
            model_name='historicalblock',
            name='fill',
        ),
        migrations.RemoveField(
            model_name='historicalblock',
            name='thickness',
        ),
    ]
