# Generated by Django 4.1 on 2022-08-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0005_remove_transition_done_alter_block_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='loc_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='loc_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
