# Generated by Django 3.2 on 2022-08-24 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0006_comment_historicalcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='block',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='block', to='diagram.block'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='block',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='diagram.block'),
        ),
    ]
