# Generated by Django 4.1 on 2022-08-06 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
        ('diagram', '0006_alter_block_loc_height_alter_block_loc_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department', to='department.department'),
        ),
    ]
