# Generated by Django 4.1 on 2022-08-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0007_alter_block_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='fill',
            field=models.CharField(blank=True, default='lightyellow', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='block',
            name='thickness',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
    ]
