# Generated by Django 3.2 on 2022-08-14 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0008_auto_20220814_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='fill',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalblock',
            name='fill',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
