# Generated by Django 4.1 on 2022-08-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0008_block_fill_block_thickness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='color',
            field=models.CharField(choices=[('pink', 'pink'), ('green', 'green'), ('black', 'black')], default='red', max_length=256),
        ),
    ]
