# Generated by Django 3.2 on 2022-08-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('diagram', '0010_auto_20220814_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalblock',
            name='user_groups',
        ),
        migrations.RemoveField(
            model_name='block',
            name='user_groups',
        ),
        migrations.AddField(
            model_name='block',
            name='user_groups',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Group'),
        ),
    ]
