# Generated by Django 4.1 on 2022-08-09 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0010_group_block_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='BlockGroup',
        ),
    ]
