# Generated by Django 4.1 on 2022-08-09 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0011_rename_group_blockgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group', to='diagram.blockgroup'),
        ),
    ]
