# Generated by Django 4.1 on 2022-08-09 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0012_alter_block_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagram.blockgroup'),
        ),
    ]
