# Generated by Django 4.1 on 2022-08-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0013_alter_block_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='transition',
            name='updated_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
