# Generated by Django 3.2 on 2022-08-09 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0001_initial'),
        ('diagram', '0014_transition_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalBlock',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('figure', models.CharField(blank=True, choices=[('Procedure', 'Procedure'), ('Cylinder1', 'Cylinder1'), ('Terminator', 'Terminator'), ('CreateRequest', 'CreateRequest'), ('Document', 'Document')], max_length=256, null=True)),
                ('description', models.CharField(max_length=256)),
                ('color', models.CharField(choices=[('pink', 'pink'), ('green', 'green'), ('black', 'black')], default='red', max_length=256)),
                ('thickness', models.IntegerField(blank=True, default=4, null=True)),
                ('fill', models.CharField(blank=True, default='lightyellow', max_length=256, null=True)),
                ('loc_height', models.IntegerField(blank=True, null=True)),
                ('loc_length', models.IntegerField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='department.department')),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='diagram.blockgroup')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical block',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
