# Generated by Django 3.2 on 2022-08-09 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0016_historicalblockgroup_historicaltransition'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='updated_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalblock',
            name='updated_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
