# Generated by Django 3.2 on 2022-08-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0017_auto_20220809_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='updated_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
