# Generated by Django 3.2 on 2022-08-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0018_alter_block_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalblock',
            name='updated_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
