# Generated by Django 3.2 on 2022-08-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0019_auto_20220809_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransition',
            name='updated_date',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='transition',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
