# Generated by Django 3.2 on 2022-08-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('diagram', '0020_auto_20220809_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='user_groups',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Group'),
        ),
    ]
