# Generated by Django 3.2 on 2022-08-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagram', '0022_auto_20220810_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='color',
            field=models.CharField(choices=[('pink', 'pink'), ('green', 'green'), ('black', 'black')], default='black', max_length=256),
        ),
        migrations.AlterField(
            model_name='historicalblock',
            name='color',
            field=models.CharField(choices=[('pink', 'pink'), ('green', 'green'), ('black', 'black')], default='black', max_length=256),
        ),
    ]
