# Generated by Django 4.1 on 2022-08-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Legal', 'Legal'), ('Risk Audit Compliance', 'RAC'), ('Human Recourse', 'HR'), ('Marketing', 'Marketing'), ('Technology', 'Tech'), ('Finance', 'Finance'), ('User Experience', 'User Experience'), ('Financial', 'Financial'), ('Business Development', 'Business Development'), ('Operation', 'Operation')], max_length=256, unique=True)),
            ],
        ),
    ]
